/* Jo-Vegi product catalog — bilingual (AR/EN) data extracted from the official export catalog */
const CATEGORIES = {
  all:    { en: "All Products", ar: "كل المنتجات" },
  veg:    { en: "Vegetables",   ar: "خضروات" },
  herbs:  { en: "Herbs & Leaves", ar: "أعشاب وورقيات" },
  legumes:{ en: "Legumes",      ar: "بقوليات" },
  fruits: { en: "Fruits",       ar: "فواكه" },
  dates:  { en: "Dates & Nuts", ar: "تمور ومكسرات" },
};

const PRODUCTS = [
  { id:"cucumber", cat:"veg", img:"img/cucumber.jpg",
    en:"Cucumber", ar:"خيار", packEn:"6–7 kg · Carton / Crate", packAr:"6–7 كغ · كرتون / قفص",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"zucchini", cat:"veg", img:"img/zucchini.jpg",
    en:"Zucchini (Kousa)", ar:"كوسا", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"pepper-green", cat:"veg", img:"img/pepper-green.jpg",
    en:"Green Pepper", ar:"فلفل أخضر", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"pepper-hot-green", cat:"veg", img:"img/pepper-hot-green.jpg",
    en:"Hot Green Pepper", ar:"فلفل حار أخضر", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"pepper-hot-red", cat:"veg", img:"img/pepper-hot-red.jpg",
    en:"Hot Red Pepper", ar:"فلفل حار أحمر", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"eggplant-black", cat:"veg", img:"img/eggplant-black.jpg",
    en:"Black Eggplant", ar:"باذنجان أسود", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"eggplant-striped", cat:"veg", img:"img/eggplant-striped.jpg",
    en:"Striped Eggplant", ar:"باذنجان مخطط", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"eggplant-classic", cat:"veg", img:"img/eggplant-classic.jpg",
    en:"Classic Eggplant (Barcelona)", ar:"باذنجان برشلونة", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"tomato", cat:"veg", img:"img/tomato.jpg",
    en:"Premium Red Tomatoes", ar:"طماطم حمراء ممتازة", packEn:"5/6/7 kg · Carton / Crate", packAr:"5/6/7 كغ · كرتون / قفص",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"bell-pepper", cat:"veg", img:"img/bell-pepper.jpg",
    en:"Colored Bell Peppers", ar:"فلفل بابريكا ملوّن", packEn:"5/6/7 kg · Carton / Crate", packAr:"5/6/7 كغ · كرتون / قفص",
    seasonEn:"Sep – May", seasonAr:"أيلول – أيار" },
  { id:"okra-indian", cat:"veg", img:"img/okra-indian.jpg",
    en:"Indian Okra", ar:"بامية هندية طويلة", packEn:"5 kg · White Crate", packAr:"5 كغ · قفص أبيض",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"faqous", cat:"veg", img:"img/faqous.jpg",
    en:"Traditional Faqous", ar:"فقوس بلدي", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"harroush", cat:"veg", img:"img/harroush.jpg",
    en:"Green Harroush", ar:"حاروش أخضر", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"squash-trad", cat:"veg", img:"img/squash-trad.jpg",
    en:"Traditional Squash", ar:"قرع بلدي", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"okra-trad", cat:"veg", img:"img/okra-trad.jpg",
    en:"Traditional Okra", ar:"بامية بلدية", packEn:"4 kg · Plastic Crate", packAr:"4 كغ · قفص بلاستيك",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },

  { id:"vine-leaves", cat:"herbs", img:"img/vine-leaves.jpg",
    en:"Vine Leaves", ar:"ورق العنب", packEn:"8 × 200g bags / crate", packAr:"8 أكياس × 200 غم / قفص",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"molokhia", cat:"herbs", img:"img/molokhia.jpg",
    en:"Molokhia Leaves", ar:"ملوخية", packEn:"8 × 200g bags / crate", packAr:"8 أكياس × 200 غم / قفص",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"thyme", cat:"herbs", img:"img/thyme.jpg",
    en:"Green Thyme (Zaatar)", ar:"زعتر أخضر", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"sage", cat:"herbs", img:"img/sage.jpg",
    en:"Green Sage", ar:"ميرامية خضراء", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"All Year Round", seasonAr:"طوال السنة" },
  { id:"herb-coriander", cat:"herbs", img:"img/herb-coriander.jpg",
    en:"Coriander", ar:"كزبرة", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-parsley", cat:"herbs", img:"img/herb-parsley.jpg",
    en:"Parsley", ar:"بقدونس", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-mint", cat:"herbs", img:"img/herb-mint.jpg",
    en:"Fresh Mint", ar:"نعنع طازج", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-purslane", cat:"herbs", img:"img/herb-purslane.jpg",
    en:"Purslane", ar:"بقلة", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-mallow", cat:"herbs", img:"img/herb-mallow.jpg",
    en:"Mallow Leaves (Khubizeh)", ar:"خبيزة", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-jute", cat:"herbs", img:"img/herb-jute.jpg",
    en:"Wild Jute (Allet)", ar:"علّت (ملوخية برية)", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"herb-dandelion", cat:"herbs", img:"img/herb-dandelion.jpg",
    en:"Dandelion Greens", ar:"هندباء", packEn:"2 kg · Plastic Crate", packAr:"2 كغ · قفص بلاستيك",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },

  { id:"snap-peas", cat:"legumes", img:"img/snap-peas.jpg",
    en:"Snap Peas", ar:"بازلاء (بلاء)", packEn:"4 kg · Carton / Crate", packAr:"4 كغ · كرتون / قفص",
    seasonEn:"Oct – May", seasonAr:"تشرين الأول – أيار" },
  { id:"broad-beans", cat:"legumes", img:"img/broad-beans.jpg",
    en:"Broad Beans", ar:"فاصوليا عريضة", packEn:"4 kg · Carton / Crate", packAr:"4 كغ · كرتون / قفص",
    seasonEn:"Oct – May", seasonAr:"تشرين الأول – أيار" },
  { id:"fine-beans", cat:"legumes", img:"img/fine-beans.jpg",
    en:"Fine Green Beans", ar:"فاصوليا رفيعة", packEn:"4 kg · Carton / Crate", packAr:"4 كغ · كرتون / قفص",
    seasonEn:"Oct – May", seasonAr:"تشرين الأول – أيار" },
  { id:"fava-green", cat:"legumes", img:"img/fava-green.jpg",
    en:"Green Fava Beans", ar:"فول بلدي أخضر", packEn:"4 kg · Carton / Crate", packAr:"4 كغ · كرتون / قفص",
    seasonEn:"Oct – May", seasonAr:"تشرين الأول – أيار" },
  { id:"lobia", cat:"legumes", img:"img/lobia.jpg",
    en:"Cowpeas (Local Lobia)", ar:"مسبلات (لوبيا بلدية)", packEn:"4 kg · Carton / Crate", packAr:"4 كغ · كرتون / قفص",
    seasonEn:"Oct – May", seasonAr:"تشرين الأول – أيار" },

  { id:"watermelon", cat:"fruits", img:"img/watermelon.jpg",
    en:"Premium Watermelon", ar:"بطيخ أحمر ممتاز", packEn:"5–7 kg · Carton / Crate", packAr:"5–7 كغ · كرتون / قفص",
    seasonEn:"May – Oct", seasonAr:"أيار – تشرين الأول" },
  { id:"green-cherries", cat:"fruits", img:"img/green-cherries.jpg",
    en:"Green Cherries", ar:"كرز أخضر", packEn:"5–7 kg · Crate / Carton", packAr:"5–7 كغ · قفص / كرتون",
    seasonEn:"Apr – Jun", seasonAr:"نيسان – حزيران" },
  { id:"strawberries", cat:"fruits", img:"img/strawberries.jpg",
    en:"Strawberries", ar:"فراولة", packEn:"Upon Request", packAr:"حسب الطلب",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"red-cherries", cat:"fruits", img:"img/red-cherries.jpg",
    en:"Red Cherries", ar:"كرز أحمر", packEn:"Upon Request", packAr:"حسب الطلب",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"stone-fruits", cat:"fruits", img:"img/stone-fruits.jpg",
    en:"Stone Fruits (Apricot · Peach · Nectarine)", ar:"فواكه ذات نواة (مشمش · خوخ · نكتارين)", packEn:"Upon Request", packAr:"حسب الطلب",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"grapes", cat:"fruits", img:"img/grapes.jpg",
    en:"Grapes", ar:"عنب", packEn:"Upon Request", packAr:"حسب الطلب",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },
  { id:"pomegranate", cat:"fruits", img:"img/pomegranate.jpg",
    en:"Pomegranates", ar:"رمان", packEn:"Upon Request", packAr:"حسب الطلب",
    seasonEn:"Upon Request", seasonAr:"حسب الطلب" },

  { id:"dates-barhi", cat:"dates", img:"img/dates-barhi.jpg",
    en:"Yellow Barhi Dates", ar:"بلح برحي أصفر", packEn:"5 kg Carton", packAr:"كرتون 5 كغ",
    seasonEn:"May – Nov", seasonAr:"أيار – تشرين الثاني" },
  { id:"dates-medjoul", cat:"dates", img:"img/dates-medjoul.jpg",
    en:"Jordanian Medjool Dates", ar:"تمر مجهول أردني", packEn:"500g – 5kg · All Grades", packAr:"500 غم – 5 كغ · كل الدرجات",
    seasonEn:"Harvest Jul – Oct", seasonAr:"القطاف تموز – تشرين الأول" },
  { id:"pistachio-red", cat:"dates", img:"img/pistachio-red.jpg",
    en:"Fresh Red Pistachios", ar:"فستق حلبي طازج أحمر", packEn:"4/5/6 kg · Crate / Carton", packAr:"4/5/6 كغ · قفص / كرتون",
    seasonEn:"Jul – Oct", seasonAr:"تموز – تشرين الأول" },
];
